name: Auto Deploy to Render (RSS trigger, 「文」部分チェック)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: RSS
        run: |
          set -e  # 失敗時に即停止
          echo "Monitoring RSS for 5 minutes..."
          for i in {1..30}; do
            latest_title=$(curl -s https://www1.x-feeder.info/lo18bx2n/rss.php \
              | xmllint --xpath "string(//item[1]/title)" - 2>/dev/null || true)

            # 空チェック
            if [ -z "$latest_title" ]; then
              sleep 10
              continue
            fi

            # 「文」部分だけ抽出
            trigger=$(echo "$latest_title" | grep -oP '「\K.*?(?=」)')

            # 空チェック
            if [ -z "$trigger" ]; then
              sleep 10
              continue
            fi

            # 文部分が start-mikanchat ならデプロイ
            if [ "$trigger" = "start-mikanchat" ]; then
              echo "Trigger detected! Deploying..."
              curl -X POST "$RENDER_DEPLOY_HOOK"
              break
            fi

            sleep 10
          done
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
