name: Auto Deploy to Render (RSS trigger loop)

on:
  workflow_dispatch:       # 手動でも起動可能
  schedule:
    - cron: "*/5 * * * *"  # 5分ごとに自動起動

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor RSS for up to 5 minutes
        run: |
          echo "deploy=0" >> $GITHUB_ENV
          echo "Monitoring RSS for 5 minutes..."
          for i in {1..30}; do   # 10秒 × 30 = 5分
            content=$(curl -s https://www1.x-feeder.info/lo18bx2n/rss.php)
            if echo "$content" | grep -q "start-mikanchat"; then
              echo "Trigger detected!"
              echo "deploy=1" >> $GITHUB_ENV
              break
            fi
            sleep 10
          done

      - name: Call Render Deploy Hook
        if: env.deploy == '1'
        run: |
          echo "Deploying to Render..."
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
