name: Auto Deploy to Render (RSS trigger, safe)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: RSS
        run: |
          echo "Monitoring RSS for 5 minutes..."
          for i in {1..30}; do
            content=$(curl -s https://www1.x-feeder.info/lo18bx2n/rss.php)
            if echo "$content" | grep -q "start-mikanchat"; then
              echo "Trigger detected! Deploying now..."
              curl -X POST "$RENDER_DEPLOY_HOOK"
              break
            fi
            sleep 10
          done
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
